--- #YAML:1.0
name:                Acme-CPANAuthors-Italian
version:             0.01
abstract:            We are Italian CPAN Authors
license:             perl
author:              
    - Aldo Calpini <dada@perl.it>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Acme::CPANAuthors:             0
    Acme::CPANAuthors::Register:   0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
